import os
from pathlib import Path

# Base structure
dirs = [
    "services/ingestion/src/ingestion/fetcher/tests",
    "services/ingestion/src/ingestion/parser/core",
    "services/ingestion/src/ingestion/parser/tests",
    "services/ingestion/src/ingestion/validator/tests",
    "services/ingestion/src/ingestion/ingestion_publisher/tests",
    "services/processing/src/processing/time_sync",
    "services/processing/src/processing/noise_filter",
    "services/processing/src/processing/feature_engineer",
    "services/processing/src/processing/band_fusion",
    "services/processing/src/processing/persistence_writer",
    "services/intelligence/src/intelligence/nowcast_solexs_detector",
    "services/intelligence/src/intelligence/nowcast_hel1os_detector",
    "services/intelligence/src/intelligence/nowcast_fusion_engine",
    "services/intelligence/src/intelligence/flare_classifier",
    "services/intelligence/src/intelligence/forecast_feature_window",
    "services/intelligence/src/intelligence/forecast_baseline_models",
    "services/intelligence/src/intelligence/forecast_deep_models",
    "services/intelligence/src/intelligence/lead_time_reconciler",
    "services/intelligence/src/intelligence/explainability_tree",
    "services/intelligence/src/intelligence/explainability_deep",
    "services/intelligence/src/intelligence/catalogue_builder",
    "services/api/src/api/auth_module",
    "services/api/src/api/rest_routes_lightcurve",
    "services/api/src/api/rest_routes_catalogue",
    "services/api/src/api/rest_routes_forecast",
    "services/api/src/api/rest_routes_explanation",
    "services/api/src/api/rest_routes_admin",
    "services/api/src/api/websocket_gateway",
    "services/api/src/api/alert_dispatcher",
    "services/api/tests",
    "services/dashboard/src/dashboard/layout_shell",
    "services/dashboard/src/dashboard/lightcurve_view",
    "services/dashboard/src/dashboard/catalogue_view",
    "services/dashboard/src/dashboard/alert_console",
    "services/dashboard/src/dashboard/explanation_view",
    "services/dashboard/src/dashboard/admin_panel",
    "services/dashboard/src/dashboard/api_client",
    "services/dashboard/assets",
    "shared/schemas",
    "shared/db/models",
    "shared/db/migrations/versions",
    "shared/config",
    "shared/exceptions",
    "shared/observability",
    "infra/docker/nginx",
    "infra/docker/prometheus",
    "infra/docker/grafana/dashboards",
    "infra/k8s",
    "airflow/dags",
    "tests/integration",
    "tests/fixtures",
    "notebooks",
    "data/raw",
    "data/quarantine",
    "data/backfill",
    ".github/workflows",
]

files = [
    ".env.example",
    "pyproject.toml",
    "docker-compose.yml",
    "docker-compose.override.yml.example",
    "Makefile",
    "services/ingestion/pyproject.toml",
    "services/ingestion/Dockerfile",
    "services/ingestion/main.py",
    "services/ingestion/src/ingestion/__init__.py",
    "services/ingestion/src/ingestion/fetcher/interface.py",
    "services/ingestion/src/ingestion/fetcher/core.py",
    "services/ingestion/src/ingestion/parser/interface.py",
    "services/ingestion/src/ingestion/parser/core/fits_parser.py",
    "services/ingestion/src/ingestion/parser/core/cdf_parser.py",
    "services/ingestion/src/ingestion/parser/core/csv_parser.py",
    "services/ingestion/src/ingestion/validator/interface.py",
    "services/ingestion/src/ingestion/validator/core.py",
    "services/ingestion/src/ingestion/ingestion_publisher/interface.py",
    "services/ingestion/src/ingestion/ingestion_publisher/core.py",
    "services/processing/pyproject.toml",
    "services/processing/Dockerfile",
    "services/processing/worker.py",
    "services/intelligence/pyproject.toml",
    "services/intelligence/Dockerfile",
    "services/intelligence/worker.py",
    "services/intelligence/src/intelligence/forecast_baseline_models/interface.py",
    "services/intelligence/src/intelligence/forecast_baseline_models/xgboost_model.py",
    "services/intelligence/src/intelligence/forecast_baseline_models/lightgbm_model.py",
    "services/intelligence/src/intelligence/forecast_baseline_models/catboost_model.py",
    "services/intelligence/src/intelligence/forecast_deep_models/interface.py",
    "services/intelligence/src/intelligence/forecast_deep_models/lstm_model.py",
    "services/intelligence/src/intelligence/forecast_deep_models/gru_model.py",
    "services/intelligence/src/intelligence/forecast_deep_models/informer_model.py",
    "services/intelligence/src/intelligence/forecast_deep_models/patchtst_model.py",
    "services/intelligence/src/intelligence/forecast_deep_models/tft_model.py",
    "services/api/pyproject.toml",
    "services/api/Dockerfile",
    "services/api/src/api/main.py",
    "services/dashboard/pyproject.toml",
    "services/dashboard/Dockerfile",
    "services/dashboard/src/dashboard/app.py",
    "shared/pyproject.toml",
    "shared/schemas/lightcurve.py",
    "shared/schemas/catalogue.py",
    "shared/schemas/forecast.py",
    "shared/schemas/explanation.py",
    "shared/schemas/auth.py",
    "shared/db/models/raw_light_curve.py",
    "shared/db/models/processed_light_curve.py",
    "shared/db/models/engineered_features.py",
    "shared/db/models/flare_catalogue.py",
    "shared/db/models/forecast_events.py",
    "shared/db/models/explanation_artifacts.py",
    "shared/db/models/model_runs.py",
    "shared/db/models/users.py",
    "shared/db/models/alerts.py",
    "shared/db/session.py",
    "shared/db/migrations/env.py",
    "shared/config/settings.py",
    "shared/config/thresholds.yaml",
    "shared/exceptions/errors.py",
    "shared/observability/logging.py",
    "shared/observability/metrics.py",
    "infra/docker/base.Dockerfile",
    "infra/docker/nginx/nginx.conf",
    "infra/docker/prometheus/prometheus.yml",
    "infra/k8s/namespace.yaml",
    "infra/k8s/ingestion-deployment.yaml",
    "infra/k8s/processing-deployment.yaml",
    "infra/k8s/intelligence-deployment.yaml",
    "infra/k8s/api-deployment.yaml",
    "infra/k8s/dashboard-deployment.yaml",
    "infra/k8s/postgres-statefulset.yaml",
    "infra/k8s/redis-deployment.yaml",
    "infra/k8s/hpa.yaml",
    "airflow/dags/ingest_solexs_dag.py",
    "airflow/dags/ingest_hel1os_dag.py",
    "airflow/dags/backfill_reprocess_dag.py",
    "airflow/dags/scheduled_forecast_dag.py",
    "airflow/dags/lead_time_reconciliation_dag.py",
    "airflow/dags/model_retraining_dag.py",
    "tests/integration/test_end_to_end_nowcast_pipeline.py",
    "tests/integration/test_end_to_end_forecast_pipeline.py",
    "tests/integration/test_api_auth_flow.py",
    "tests/fixtures/sample_solexs_l1.fits",
    "tests/fixtures/sample_hel1os_l1.fits",
    "tests/fixtures/synthetic_flare_events.json",
    "notebooks/01_explore_solexs_raw.ipynb",
    "notebooks/02_explore_hel1os_raw.ipynb",
    "notebooks/03_flare_light_curve_shape_analysis.ipynb",
    "notebooks/04_feature_engineering_prototyping.ipynb",
    "notebooks/05_baseline_model_prototyping.ipynb",
    "notebooks/06_deep_model_prototyping.ipynb",
    ".github/workflows/ci.yml",
    ".github/workflows/cd.yml",
    ".github/workflows/docs-lint.yml",
]

# Ensure we're in the right directory
base_dir = Path("c:/Users/ASUS/Desktop/bytecoding/HeliosAI")

for d in dirs:
    path = base_dir / d
    path.mkdir(parents=True, exist_ok=True)
    (path / "__init__.py").touch(exist_ok=True)

for f in files:
    path = base_dir / f
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix == ".py" and path.name != "__init__.py":
        pass # will touch it below
    path.touch(exist_ok=True)

print("Scaffolding complete.")
