apiVersion: v1
kind: Service
metadata:
  name: heliosai-api-service
  namespace: heliosai
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
